/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pl_com_training_TestJNI */

#ifndef _Included_pl_com_training_TestJNI
#define _Included_pl_com_training_TestJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pl_com_training_TestJNI
 * Method:    helloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pl_com_training_TestJNI_helloWorld
  (JNIEnv *, jobject);

/*
 * Class:     pl_com_training_TestJNI
 * Method:    returnHelloWorld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_pl_com_training_TestJNI_returnHelloWorld
  (JNIEnv *, jobject);

/*
 * Class:     pl_com_training_TestJNI
 * Method:    sayHelloToName
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_pl_com_training_TestJNI_sayHelloToName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     pl_com_training_TestJNI
 * Method:    createUser
 * Signature: ()Lpl/com/training/User;
 */
JNIEXPORT jobject JNICALL Java_pl_com_training_TestJNI_createUser
  (JNIEnv *, jobject);

/*
 * Class:     pl_com_training_TestJNI
 * Method:    sayHelloToUser
 * Signature: (Lpl/com/training/User;)Ljava/lang/String;
 */
JNIEXPORT void JNICALL Java_pl_com_training_TestJNI_sayHelloToUser
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
